---
title: 'QUANT ASSIGN #2'
output: pdf_document
date: "2025-10-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
cat("\014")

setwd("/Users/ben/Desktop/QUANT/ASSIGN 2/")

library(quantmod)
library(stats)
library(forecast)
library(jtools)
library(texreg)
library(fBasics)
library(dplyr)
library(rugarch)
```

```{r}
#DATA COLLECTION

getSymbols("KO", from = "2019-09-01", to = "2025-08-31", periodicity = "daily")

ret <- diff(log(KO$KO.Adjusted))*100 
ret <- na.omit(ret) 

basicStats(ret)

plot(ret)
```


```{r}
### VOLATILITY ANALYSIS PART 1 ###

T1 <- length(ret["/2022-08-30"])
T2 <- length(ret["2022-08-31/"])

# 3 Models - Arch, GARCH, GJR GARCH

#ARCH1 MODEL

arch1 = ugarchspec(variance.model = list(model="sGARCH",garchOrder = c(1,0)),
                                        mean.model = list(armaOrder = c(0,0)),
                                        distribution.model="norm")

arch1 = ugarchfit(spec=arch1, data =ret, out.sample = T2)
show(arch1)

vol_arch1=sigma(arch1)
plot(vol_arch1,type = "l")


    #GARCH 11 model 

garch1 = ugarchspec(variance.model = list(model="sGARCH",garchOrder = c(1,1)),
                                        mean.model = list(armaOrder = c(0,0)),
                                        distribution.model="norm")

garch1 = ugarchfit(spec=garch1, data =ret, out.sample = T2)
show(garch1)

vol_garch1=sigma(garch1)
plot(vol_garch1,type = "l")


    #GJR-GARCH MODEL

gjr11 = ugarchspec(variance.model = list(model = "gjrGARCH", garchOrder = c(1,1)),
                  mean.model = list(armaOrder = c(0, 0)),
                  distribution.model = "norm")
# fit the model
gjr11 = ugarchfit(spec = gjr11, data = ret, out.sample = T2)
show(gjr11)

vol_gjr11=sigma(gjr11)
plot(vol_gjr11,type = "l")

```

```{r}
#VOLATILITY PART 2 GJR GARCH


# Select GJR GARCH AND GARCH 1,1 lowest AIC and BIC 

#using Rolling window to account for short periods of high volatility 

### rolling window estimation for gjr 


gjr11 = ugarchspec(variance.model = list(model = "gjrGARCH", garchOrder = c(1,1)),
                  mean.model = list(armaOrder = c(0, 0)),
                  distribution.model = "norm")

gjrroll = ugarchroll(gjr11, ret, n.start = T1, refit.every = 10,
                  refit.window = "moving")


show(gjrroll)

slotNames(gjrroll)
str(gjrroll@forecast)

dates_oos <- index(ret[(T1+1):(T1+T2)])

# retrieve one-day-ahead volatility forecast
vol_gjr_roll = gjrroll@forecast$density$Sigma
# redefine an xts object to store volatility forecasts
vol_gjr_roll = xts(vol_gjr_roll,order.by = dates_oos)

plot(vol_gjr_roll)

head(vol_gjr_roll)
tail(vol_gjr_roll)

# retrieve one-day-ahead volatility forecast
vol_gjr_roll = gjrroll@forecast$density$Sigma
# redefine an xts object to store volatility forecasts
vol_gjr_roll = xts(vol_gjr_roll,order.by = dates_oos)

# save the realized returns in the out-of-sample period to use as a proxy
realizedret = ret[(T1+1):(T1+T2)]

# compute the squared forecast error
se_gjr_roll = (vol_gjr_roll^2-realizedret^2)^2
plot(se_gjr_roll)
#dev.copy(pdf,'Figures/L10_se_arch_roll.pdf', width = 6, height = 4,paper='special')
#dev.off()

mse_gjr_roll=mean(se_gjr_roll)


```


```{r}
#rolling window estimation for GARCH

garch1 = ugarchspec(variance.model = list(model="sGARCH",garchOrder = c(1,1)),
                                        mean.model = list(armaOrder = c(0,0)),
                                        distribution.model="norm")

garroll = ugarchroll(garch1, ret, n.start = T1, refit.every = 10,
                  refit.window = "moving")


show(garroll)

slotNames(garroll)
str(garroll@forecast)

# retrieve one-day-ahead volatility forecast
vol_gar_roll = garroll@forecast$density$Sigma
# redefine an xts object to store volatility forecasts
vol_gar_roll = xts(vol_gar_roll,order.by = dates_oos)

plot(vol_gar_roll)

head(vol_gar_roll)
tail(vol_gar_roll)

# retrieve one-day-ahead volatility forecast
vol_gar_roll = garroll@forecast$density$Sigma
# redefine an xts object to store volatility forecasts
vol_gar_roll = xts(vol_gar_roll,order.by = dates_oos)

# save the realized returns in the out-of-sample period to use as a proxy
realizedret = ret[(T1+1):(T1+T2)]

# compute the squared forecast error
se_gar_roll = (vol_gar_roll^2-realizedret^2)^2
plot(se_gar_roll)
#dev.copy(pdf,'Figures/L10_se_arch_roll.pdf', width = 6, height = 4,paper='special')
#dev.off()

mse_gar_roll=mean(se_gar_roll)

```


